# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransactionsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import Transaction, messages

class Ui_MainWindow(QtWidgets.QMainWindow):
    t_services = Transaction.transaction_services()
    transactions = [] #the length is used to check if it is empty or not through out this file
    
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        uic.loadUi('TransactionsUI.ui', self)
        self.show()
        
        #added by me
        self.prepare_table()
        self.transactions = self.t_services.getExpenses()
        self.populate_table(self.transactions)
        self.btnSearch_2.clicked.connect(self.btnSearch_funtion)
        self.cmbTransactionType.addItems(["expense", "income"])
        self.cmbMode.activated.connect(self.mode_selection)
        self.btnAddTransaction_2.clicked.connect(self.btnAdd_function)


        
    def prepare_table(self):
        self.tblTransactions_2.setColumnCount(5)
        self.tblTransactions_2.setHorizontalHeaderLabels(["Transaction_ID", "Transaction Type", "Date", "Category", "Amount"])
        for i in range(0, 5):
            self.tblTransactions_2.setColumnWidth(i, 164)

            
    def populate_table(self, transactions_arr):
        self.tblTransactions_2.setRowCount(0)#clearing the table
        t_list = list(transactions_arr)
        for i in range(0, len(transactions_arr)):
            self.tblTransactions_2.insertRow(i)

            self.tblTransactions_2.setItem(i, 0, QtWidgets.QTableWidgetItem(str(t_list[i].getTransactionId())))
            self.tblTransactions_2.setItem(i, 1, QtWidgets.QTableWidgetItem(t_list[i].getTransactionType()))
            self.tblTransactions_2.setItem(i, 2, QtWidgets.QTableWidgetItem(t_list[i].getDate()))
            self.tblTransactions_2.setItem(i, 3, QtWidgets.QTableWidgetItem(t_list[i].getCategory()))
            self.tblTransactions_2.setItem(i, 4, QtWidgets.QTableWidgetItem(str(t_list[i].getAmount())))

            
    def add_transactions(self):
        transactions_to_be_added = self.getTransactions_from_table()
        
        if(len(transactions_to_be_added) == 0):
            message = "There are no transactions entered. Please enter at least one transaction"
            title = "Error :("
            messages.display_message(message, title, messages.ERROR_MSG)
        
        else:
            message = """Are you sure you want to add these?, Please Make sure all details are correct
                        searching by criteria  just to fix one is gonna be a pain unless you know the transaction ID"""
            title = "Mmmmmmm"
            add_transactions_to_database = messages.display_option_message(message, title)
            if (add_transactions_to_database == True):
                for i in range(0, len(transactions_to_be_added)):
                    self.t_services.add_transaction(transactions_to_be_added[i])
                message = "Transactions added successfully"
                title = "yay :)"
                messages.display_message(message, title, messages.INFO_MSG)
            else:
                message = "Do you wish to restore the previous list of transactions?"
                title = "Do you though?"
                restore_flag = messages.display_option_message(message, title)
                if restore_flag ==  True:
                    self.populate_table(self.transactions)
                else:
                    self.clear_table()

   
    def getTransactions_from_table(self):
        
        number_of_transactions = self.tblTransactions_2.rowCount()
        transactions = []
        for i in range(0, number_of_transactions):
            transaction_id = str(self.tblTransactions_2.item(i, 0))
            transaction_type = str(self.tblTransactions_2.item(i, 1))
            t_date = str(self.tblTransactions_2.item(i, 2))
            category = str(self.tblTransactions_2.item(i, 3))
            amount = float(self.tblTransactions_2.item(i, 4))
            transaction_t = Transaction.transaction(transaction_id, amount, category, transaction_type, t_date)
            transactions.append(transaction_t)
            
        return transactions

                
    def fetch_transactions(self):
        search_by_category = self.chkboxCategory.isChecked()
        search_by_transaction_type = self.chkboxTransactionType.isChecked()
        search_by_specific_date = self.radSpecificDate.isChecked()
        search_by_month_and_year = self.radMonthYear.isChecked()
        
        t_id = None
        date = None
        category = None
        t_type = None
        
        if search_by_category == True:
            category = self.cmbCategory.currentText()
        if search_by_transaction_type == True:
            t_type = self.cmbTransactionType.currentText()
        if search_by_specific_date ==True:
            date = self.dtSpecificDate.text()
        if search_by_month_and_year == True:
            date = self.cmbMonth.text() + '-' + self.txtYear.text()
        
        self.transactions = self.t_services.getTransactions(t_id, date, category, t_type)
        if(len(self.transactions) >= 1):
            self.tblTransactions_2.setRowCount(0)
            self.populate_table(self.transactions)
        else:
            message = "No Transactions that meet the search criteria were found"
            title = "Operation Failed"
            messages.display_message(message, title, messages.ERROR_MSG)

    
    def clear_table(self):
        self.tblTransactions_2.setRowCount(0)

    
    def mode_selection(self):
        if self.cmbMode.currentText() == "Add Transaction":
            self.clear_table()        
            self.btnSearch_2.setText("Insert New Blank Row")
            self.btnUpdate.setText("Clear Current Row")
            self.btnDelete.setText("Delete Row")
            
                     
        else:
            self.btnSearch_2.setText("Search")
            self.btnUpdate.setText("Update")
            self.btnDelete.setText("Delete")
            
            message = "Do you want to load the previous transactions?"
            title = "Load Previous Transactions"
            
            if len(self.transactions) >= 1:
                r = messages.display_option_message(message, title, messages.INFO_MSG)
                if r == True:
                    self.populate_table(self.transactions)


    def btnSearch_funtion(self):
        if self.cmbMode.currentText() == "Add Transaction":
            #in this case the button will be in insert empty row mode
            position = self.tblTransactions_2.rowCount()
            self.tblTransactions_2.insertRow(position)
            self.tblTransactions_2.setItem(position, 0, QtWidgets.QTableWidgetItem(str(Transaction.generate_ID())))
        else:
            #button will be in search mode
            self.fetch_transactions()

    def btnAdd_function(self):
        if self.cmbMode.currentText() == "Add Transaction":
            self.add_transactions()
        
        else:
            message = "Functionality of this button is disabled in this mode"
            title = "oopsie *_*"
            messages.display_message(message, title, messages.INFO_MSG)
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_MainWindow()
    app.exec_()
